#
# requirements
# - install pre-commit (latest)
# - install terraform-docs (latest)
# - see .github/workflows/ci-pull-request.yaml for more info on what's being valiated on CI
# $ pre-commit run --color=always --show-diff-on-failure --all-files
#


repos:
  # https://github.com/antonbabenko/pre-commit-terraform/blob/master/README.md#terraform_validate (point 4)
  - repo: local
    hooks:
      - id: terraform_clean
        name: "Terraform Cleanup"
        pass_filenames: false
        language: system
        entry: bash -c "find . \( -iname ".terraform*" ! -iname ".terraform-docs*" ! -path "*/test/*" \)  -print0 | xargs -0 rm -r; true"

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.64.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
        args:
          - '--args=--sort-by required'
      - id: terraform_tflint
        exclude: (test)|(examples)\/.*$
        args:
          - '--args=--only=terraform_comment_syntax'
          - '--args=--only=terraform_deprecated_index'
          - '--args=--only=terraform_deprecated_interpolation'
          - '--args=--only=terraform_documented_outputs'
          - '--args=--only=terraform_documented_variables'
          - '--args=--only=terraform_module_pinned_source'
          - '--args=--only=terraform_module_version'
          - '--args=--only=terraform_naming_convention'
          - '--args=--only=terraform_required_providers'
          - '--args=--only=terraform_required_version'
          - '--args=--only=terraform_standard_module_structure'
          - '--args=--only=terraform_typed_variables'
          - '--args=--only=terraform_unused_declarations'
          - '--args=--only=terraform_unused_required_providers'
          - '--args=--only=terraform_workspace_remote'
      # https://github.com/antonbabenko/pre-commit-terraform#terraform_validate
      - id: terraform_validate
        exclude: (test)|(examples)\/.*$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
